# Generated by Django 4.1.6 on 2023-02-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-date'], 'verbose_name': 'return', 'verbose_name_plural': 'returns'},
        ),
    ]
